blog/urls.py
#url mappings for blog
from . import views
from django.conf.urls import include,url
app_name= 'blog'
urlpatterns = [
    url(r'^$',views.top_blogs,name='index'), #define the homepage for this
    url(r'^blogs/$',views.blogs,name='all_blogs'),
    url(r'^blog/(?P<blog_id>[0-9]+)/',views.blog,name='blog'),
]

dexblog/urls.py
#url mappings
from django.contrib import admin
from django.conf.urls import include,url
from django.conf import settings 
from django.conf.urls.static import static
urlpatterns = [
	url(r'^', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^myblog/', include('blog.urls')),
]

if settings.DEBUG:
	print(settings.STATIC_URL, settings.STATIC_ROOT)
	urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url
from . import views
app_name= 'music'
urlpatterns=[
	#/music/
	# url(r'^$',views.index,name ='index'),
	url(r'^$',views.index,name='index'), # using generic/class
	url(r'^login/$',views.LoginView.as_view(),name='login'),
	url(r'^logout/$',views.logout_user,name='logout'),
	url(r'^register/$',views.UserFormView.as_view(),name='register'),
	#/music/21/
	#()-group as 21 not as 2 and 1 seperated, ?P<album_id>=>store 21 into album_id var
	#url(r'^(?P<album_id>[0-9]+)/$',views.detail,name='detail') ,	using function in views
	url(r'^(?P<pk>[0-9]+)/$',views.detail,name='detail'), #using generic/class , it expects pk so use pk
	#/music/<album_id>/favorite
	#url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite,name='favorite'), 	
	#/music/album/add/
	url(r'^album/add/$',views.AlbumCreate.as_view(),name='album_add'),
	#/music/album/2/
	url(r'^album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(),name='album_edit'),
	#music/1/create_songs
	url(r'^(?P<pk>[0-9]+)/add/$',views.create_song,name='create_song'),
	#1/favorite
	url(r'^(?P<song_id>[0-9]+)/favorite$',views.favorite_song,name='favorite'),
	#/music/album/2/delete/1/
	url(r'(?P<pk>[0-9]+)/song/(?P<song_id>[0-9]+)/$',views.delete_song,name='delete_song'),
	#mu
	url(r'^album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(),name='album_delete'),
]

music/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import Permission,User
# Create your models here.
class Album(models.Model):
	# id = models.Integer()
	user = models.ForeignKey(User,default=2,on_delete=models.CASCADE)
	artist = models.CharField(max_length=256)
	album_title = models.CharField(max_length=512)
	genre = models.CharField(max_length=64)
	album_logo = models.FileField()

	def get_absolute_url(self):
		return reverse('music:detail',kwargs={'pk':self.pk})

	def __str__(self):
		return self.album_title+' by '+self.artist
#needs to be associated with Album/specification of Album
class Song(models.Model):
	#total dependency if album is deleted song is deleted
	album = models.ForeignKey(Album,on_delete=models.CASCADE) 
	file_type = models.CharField(max_length = 8)
	song_title = models.CharField(max_length = 256)
	song_url = models.CharField(max_length=512,default="")
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title+' - '+self.file_type

music/forms.py
from django.contrib.auth.models import User
from .models import Song,Album
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username','email','password']

class SongForm(forms.ModelForm):
	class Meta:
		model = Song
		fields = ['song_title','file_type','is_favorite','song_url']

class AlbumForm(forms.ModelForm):
	class Meta:
		model = Album
		fields = ['artist','album_title','genre','album_logo']

class LoginForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username','password']

		
		

music/views.py
from django.views import generic
from django.http import JsonResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth import authenticate,login,logout
from .models import Album,Song
from django.urls import reverse_lazy
from .forms import UserForm,LoginForm,SongForm
from django.views.generic.base import View

#Using generic/class
'''class IndexView(generic.ListView):
	template_name = 'music/index.html'
	context_object_name = 'all_albums' #default value is 'object_list'

	def get_queryset(self,request):
		if not request.user.is_authenticated():
			return render(request,'music/login.html')
		else:
			albums = Album.objects.filter(user=request.user)'''
def index(request):
	if not request.user.is_authenticated:
		return redirect('music:login')
	else:
		albums = Album.objects.filter(user=request.user)
		return render(request,'music/index.html',{'all_albums':albums})

def detail(request,pk):
	if not request.user.is_authenticated:
		return render(request,'music/login.html')
	else:
		user = request.user
		album = get_object_or_404(Album,pk=pk)
		return render(request,'music/details.html',{'album':album,'user':user})

class AlbumCreate(CreateView):
	model = Album
	fields=['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
	model = Album
	fields=['artist','album_title','genre','album_logo']

class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('music:index')

class SongCreate(CreateView):
	model = Song
	fields = ['album','file_type','song_title','is_favorite']

class UserFormView(View):
	form_class = UserForm
	template_name = 'music/registration_form.html'

	#display blank form
	def get(self,request):
		form = self.form_class(None)
		return render(request,self.template_name,{'form':form})
	#process form data
	def post(self,request):
		form = self.form_class(request.POST) #contains all contents of form

		if form.is_valid():
			#create an object from form but doesnot save at database yet
			user = form.save(commit=False)

			#clean (normalized) data => properly formatted
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			#returns Use objects if credentials correct
			user = authenticate(username=username,password=password)

			if user is not None:
				#check if user is active
				if user.is_active:
					login(request,user)
					return redirect('music:index')
		return render(request,self.template_name,{'form':form})

class LoginView(View):
	form_class = LoginForm
	template_name = 'music/login.html'

	def get(self,request):
		form = self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		print('Post login')
		form = self.form_class(request.POST)
			
		print('Form valid')
		username = request.POST['username']
		password = request.POST['password']
	#authenticate user credentials
		user = authenticate(username=username,password=password)
		if user is not None:
			if user.is_active:
				login(request,user)
				albums = Album.objects.filter(user=request.user)
				return render(request,'music/index.html',{'all_albums':albums,'user':request.user.username})
			else:
				return render(request,self.template_name,{'err_msg':'Your account has been disabled. Contact the administrator.','form':form})
		else:
			return render(request,self.template_name,{'err_msg':'Invalid Login.','form':form})
		return render(request,self.template_name,{'form':form})


def logout_user(request):
	logout(request)
	return redirect('music:index')

def create_song(request,pk):
	form =  SongForm(request.POST or None,)
	album = get_object_or_404(Album,pk=pk)
	if form.is_valid():
		albums_songs = album.song_set.all()
		for s in albums_songs:
			if s.song_title == form.cleaned_data.get("song_title"):
				context={
					'album':album,
					'form':form,
					'error_message': 'You already added that song',
				}
				return render(request,'music/song_form.html',context)
		song = form.save(commit=False)
		song.album = album
		song.save()

	return render(request,'music/song_form.html',{'album':album,'form':form})

def delete_song(request,pk,song_id):
	album = get_object_or_404(Album,pk=pk)
	song = Song.objects.get(pk=song_id)
	song.delete()
	return render(request,'music/details.html',{'album':album})

def favorite_song(request,song_id):
	song = get_object_or_404(Song,pk=song_id)
	try:
		if song.is_favorite:
			song.is_favorite = False
		else:
			song.is_favorite = True
		song.save()
	except (KeyError,Song.DoesNotExist):
		return JsonResponse({'success':False})
	else:
		return JsonResponse({'success':True})

music/templates/music/album_form.html
{% extends 'music/base.html'%}
{% block title%}Add New Album{%endblock%}
{% block  body%}
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 col-md-7">
				<div class="panel panel-default">
					<div class="panel-body">
						<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
							{%csrf_token%}
							{% include 'music/form_template.html' %}
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<button type="submit" class="btn btn-success">Submit</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

{%endblock%}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load staticfiles %}
<link rel="shortcut icon" href="{% static 'music/favicon.ico' %}">
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<title>DexterBlogs</title>

<!-- Bootstrap core CSS -->


<link href="{% static 'music/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet" />


<!-- Custom styles for this template -->
<link href="{% static 'music/bootstrap-3.3.7-dist/css/style.css' %}" rel="stylesheet" /> 

<!-- Load Javascript files  -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="{% static 'music/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
</head>
<body>
	<!--Navbar-->
	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Header -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">DexterBlogs</a>
    </div>

    <!-- Items -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-cd"></span>&nbsp;Albums</a></li>
        <li class=""><a href="#"><span class="glyphicon glyphicon-music"></span>&nbsp;Songs</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="Search" method="GET" action="#">
        <div class="form-group">
          <input type="text" class="form-control" name="q" value="" placeholder="Search">
        </div>
        <button type="submit"><span class="glyphicon glyphicon-search"></span></button>
      </form>
      <ul class="nav navbar-nav navbar-right">

          <li class=""><a href="{% url 'music:album_add'%}"><span class="glyphicon glyphicon-user"></span> Hi, {{user}}</a></li>

      		<li class=""><a href="{% url 'music:album_add'%}"><span class="glyphicon glyphicon-plus"></span> Add Albums</a></li>
      		<li class=""><a href="{% url 'music:logout' %}"><span class="glyphicon glyphicon-off"></span> LogOut</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block body%}
{% endblock %}
</body>
</html>

music/templates/music/details.html
{% extends 'music/base.html' %}
{% block title %} Album Details {% endblock %}
{% block body %}
<div class="main container-fluid">
	<div class="row">
		<div class="col-sm-2 col-md-2">
			<img src="{{album.album_logo.url}}" width="200px" height="200px">
			<h1>{{album.album_title}}</h1>
			<h3>{{album.artist}}</h3>
			<a href="{% url 'music:album_edit' album.id%}">Edit album</a>
			{% if err_msg %}
			<p><strong>{{err_msg}}</strong></p>
			{% endif%}
			<ul>
				{% for song in album.song_set.all %}
				<label for="song{{ forloop.counter }}">
					{{song.song_title}}
					{% if song.is_favorite%}
						<img src="http://i.imgur.com/b9b13Rd.png"/>
					{%endif%}
				</label>
				<br/>
				{% endfor %}
			</ul>
		</div>
		<div class=" col-sm-10 col-md-10">
			<button class="btn btn-primary">View All</button>
			<a href="{%url 'music:create_song' album.id %}"><button class="btn btn-default" style="display: inline;">Add New Song</button></a>
			<table class="table table-striped table-hover" style="margin: 5px">
				<h2 style="margin: 3px">All Songs</h2>
				<thead class="thead-dark">
					<tr>
						
						<th scope="col">Title</th>
						<th scope="col">Audio File</th>
						<th scope="col">Favorite</th>
						<th scope="col">Actions</th>
					</tr>
				</thead>
				<tbody>
				{% for song in album.song_set.all %}
					<tr>

						<td>{{song.song_title}}</td>
						<td>
							<a href="{{song.song_url}}">
							<button type="button" call="btn btn-success btn-xs">
								<span class="glyphicon glyphicon-play">&nbsp;Play</span>
							</button>
							</a>
						</td>
						  <td>
                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                          </td>
                        <td><form action="{% url 'music:delete_song' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                        </td>
					</tr>
				{%endfor%}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

music/templates/music/form_template.html
{%for field in form%}
	<div class="form-group">
		{%if not err_msg%}
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		{%endif%}
		<label class="control-label col-sm-2">{{field.label_tag}}</label>
		<div class="col-sm-10">{{field}}</div>
	</div>
{%endfor%}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
<div class="main container-fluid">
	<h1>Albums List</h1>
	{% if all_albums %}
		<div class='row'>
			
		{% for album in all_albums %}
			<div class = "col-sm-4 col-lg-2">
			<div class="album thumbnail">
			<a href="{%url 'music:detail' album.id %}"><img src='{{album.album_logo.url}}' alt='{{album.album_title}}'/></a>
			<div class="caption">
				<h2>{{album.album_title}}</h2>
				<h4>{{album.artist}}</h4>
			</div>
			<a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
			<form action="{% url 'music:album_delete' album.id %}" method="POST" style="display: inline;">{%csrf_token%}<button type="submit" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-trash"></span></button></form>
			</div>
			</div>

		{%endfor%}
			
		</div>

		{% else %}
		
	<p>You don't have any albums</p>
	{% endif %}

</div>

{% endblock %}

music/templates/music/login.html
{% extends 'music/base.html'%}
{% block title%}Login{%endblock%}
{% block  body%}
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 col-md-7">
				<div class="panel panel-default">
					<div class="panel-body">
						<h3>Login</h3>
						{%if err_msg%}
						<p><strong class="danger">{{err_msg}}</strong></p>
						{%endif%}
						<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
							{%csrf_token%}
							{% include 'music/form_template.html' %}
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<button type="submit" class="btn btn-success">Submit</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

{%endblock%}

music/templates/music/registration_form.html
{% extends 'music/base.html'%}
{% block title%}Register{%endblock%}
{% block  body%}
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 col-md-7">
				<div class="panel panel-default">
					<div class="panel-body">
						<h3>Create a New Account</h3>
						<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
							{%csrf_token%}
							{% include 'music/form_template.html' %}
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<button type="submit" class="btn btn-success">Submit</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

{%endblock%}

music/templates/music/song_form.html
{% extends 'music/base.html'%}
{% block title%}Add New Song{%endblock%}
{% block  body%}
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 col-md-7">
				<div class="panel panel-default">
					<div class="panel-body">
						<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
							{%csrf_token%}
							{% include 'music/form_template.html' %}
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<button type="submit" class="btn btn-success">Submit</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

{%endblock%}