blog/urls.py
#url mappings for blog
from . import views
from django.conf.urls import include,url
app_name= 'blog'
urlpatterns = [
    url(r'^$',views.top_blogs,name='index'), #define the homepage for this
    url(r'^blogs/$',views.blogs,name='all_blogs'),
    url(r'^blog/(?P<blog_id>[0-9]+)/',views.blog,name='blog'),
]

dexblog/urls.py
#url mappings
from django.contrib import admin
from django.conf.urls import include,url
from django.conf import settings 
from django.conf.urls.static import static
urlpatterns = [
	url(r'^', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^myblog/', include('blog.urls')),
]

if settings.DEBUG:
	print(settings.STATIC_URL, settings.STATIC_ROOT)
	urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url
from . import views
app_name= 'music'
urlpatterns=[
	#/music/
	# url(r'^$',views.index,name ='index'),
	url(r'^$',views.index,name='index'), # using generic/class
	url(r'^login/$',views.LoginView.as_view(),name='login'),
	url(r'^logout/$',views.logout_user,name='logout'),
	url(r'^register/$',views.UserFormView.as_view(),name='register'),
	#/music/21/
	#()-group as 21 not as 2 and 1 seperated, ?P<album_id>=>store 21 into album_id var
	#url(r'^(?P<album_id>[0-9]+)/$',views.detail,name='detail') ,	using function in views
	url(r'^(?P<pk>[0-9]+)/$',views.detail,name='detail'), #using generic/class , it expects pk so use pk
	#/music/<album_id>/favorite
	#url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite,name='favorite'), 	
	#/music/album/add/
	url(r'^album/add/$',views.AlbumCreate.as_view(),name='album_add'),
	#/music/album/2/
	url(r'^album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(),name='album_edit'),
	#music/1/create_songs
	url(r'^(?P<pk>[0-9]+)/add/$',views.create_song,name='create_song'),
	#1/favorite
	url(r'^(?P<song_id>[0-9]+)/favorite$',views.favorite_song,name='favorite'),
	#/music/album/2/delete/1/
	url(r'(?P<pk>[0-9]+)/song/(?P<song_id>[0-9]+)/$',views.delete_song,name='delete_song'),
	#mu
	url(r'^album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(),name='album_delete'),
]

blog/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class Blog(models.Model):
	blog_title = models.CharField(max_length=512)
	author = models.CharField(max_length=256)
	date = models.DateTimeField(default=datetime.now())
	media = models.CharField(max_length=256)
	article = models.TextField()
	category = models.CharField(max_length=32)

	def __str__(self):
		return self.blog_title+' by '+self.author

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Blog
# Create your views here.
def blogs(request):
	all_blogs = Blog.objects.all()
	content = {'all_blogs':all_blogs}
	return render(request,'blog/blogs.html',content)

def blog(request,blog_id):
	blog = get_object_or_404(Blog,pk=blog_id)
	content = {'blog':blog}
	return render(request,'blog/blog.html',content)

def top_blogs(request):
	top = []
	for x in [1,2]:
		blog = get_object_or_404(Blog,pk=x)
		top.append(blog)
	content = {'top':top}
	return render(request,'blog/index.html',content)

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load staticfiles %}
<link rel="icon" href="{% static 'blog/favicon.ico' %}">
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<title>DexterBlogs</title>

<!-- Bootstrap core CSS -->
<link href="{% static 'blog/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet" />



<!-- Custom styles for this template -->
<link href="{% static 'blog/bootstrap-3.3.7-dist/css/style.css' %}" rel="stylesheet" /> 

<!-- Load Javascript files  -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="{% static 'blog/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
</head>
<body id="myBody">
	<!--Navbar-->
	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Header -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'blog:index' %}">DexterBlogs</a>
    </div>

    <!-- Items -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href="{%url 'blog:all_blogs' %}"><span class="glyphicon glyphicon-blog"></span>&nbsp;Blogs</a></li>
        <li class=""><a href="{%url 'music:index' %}"><span class="glyphicon glyphicon-music"></span>&nbsp;My Music</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="Search" method="GET" action="#">
        <div class="form-group">
          <input type="text" class="form-control" name="q" value="" placeholder="Search">
        </div>
        <button type="submit"><span class="glyphicon glyphicon-search"></span></button>
      </form>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block body%}
{% endblock %}
</body>
</html>

blog/templates/blog/blog.html
{% extends 'blog/base.html' %}

{% block body %}

	{% if blog %}
	<div>
		<h2>{{blog.blog_title}}</h2>
		<p>{{blog.author}}</p>
		<p>{{blog.date}}</p>
		<p>{{blog.category}}</p>
		<img src="{{blog.media}}" style="width: 80px ; height: 80px" />
		<p>{{blog.article}}</p>
	</div>
	{%endif%}
{% endblock %}

blog/templates/blog/blogs.html
{% extends 'blog/base.html' %}

{% block body %}
<h2>All blogs</h2>
<div style="margin: 5px 10px">
{% if all_blogs %}
	{% for blog in all_blogs %}
		<div class='blogs_list' style="box-shadow:5px 5px 5px grey;">
			<h3><a href="{% url 'blog:blog' blog.id%}">{{blog.blog_title}}</a></h3>
			<p>{{blog.author}}</p>
			<p>{{blog.date}}</p>
		</div>
	{% endfor %}
{%endif%}

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block body %}
<h2>Top blogs</h2>
<div style="margin: 5px 10px">
{% if top %}
	{% for blog in top %}
		<div class='blogs_list' style="box-shadow:5px 5px 5px grey;">
			<h3><a href="{% url 'blog:blog' blog.id%}">{{blog.blog_title}}</a></h3>
			<p>{{blog.author}}</p>
			<p>{{blog.date}}</p>
		</div>

	{% endfor %}
{%endif%}
</div>
{% endblock %}